<a href="https://colab.research.google.com/github/srk1964/TensorFlow/blob/ClassFiles/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

in this notebook we are going to conver some of the most fundamental concepts of Tensorflow

In [ ]:
# import tensorflow
import tensorflow as tf
print(tf.__version__)

2.19.0


In [ ]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
scalar.ndim

0

In [ ]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
matrix = tf.constant([[[10.,7.,5.]]],dtype=tf.float16)
matrix.ndim

3

In [ ]:
import pandas as pd
fp = 'http://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
df = pd.read_csv(fp, names=['sepal_length','sepal_width','petal_length','petal_width','species'],header=None)
df

,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,Iris-setosa
1,4.9,3.0,1.4,0.2,Iris-setosa
2,4.7,3.2,1.3,0.2,Iris-setosa
3,4.6,3.1,1.5,0.2,Iris-setosa
4,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Iris-virginica
146,6.3,2.5,5.0,1.9,Iris-virginica
147,6.5,3.0,5.2,2.0,Iris-virginica
148,6.2,3.4,5.4,2.3,Iris-virginica


In [ ]:
   x = tf.constant([[1,2,1],[0,1,0],[2,3,4]])
y = tf.constant([[2,5],[6,7],[1,8]])
print(x)
print(y)
tf.matmul(x,y)

tf.Tensor(
[[1 2 1]
 [0 1 0]
 [2 3 4]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[2 5]
 [6 7]
 [1 8]], shape=(3, 2), dtype=int32)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[15, 27],
       [ 6,  7],
       [26, 63]], dtype=int32)>

In [ ]:
x = tf.constant([[41,12],[20,17],[82,43]])
tf.math.reduce_std(tf.cast(x,dtype=tf.float64))
x

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[41, 12],
       [20, 17],
       [82, 43]], dtype=int32)>

In [ ]:
x = tf.constant([[41,12,34],[20,17,12],[82,43,78]])
print(tf.matmul(x,y),end='\n*********\n')
tf.math.reduce_prod(x)

tf.Tensor(
[[ 188  561]
 [ 154  315]
 [ 500 1335]], shape=(3, 2), dtype=int32)
*********


<tf.Tensor: shape=(), dtype=int32, numpy=1719923200>

In [ ]:
# import tensorflow
import tensorflow as tf
tf.random.set_seed(42)
x = tf.cast(tf.random.uniform(shape=[52,7],minval=5,maxval=200),tf.int16)
#print(x,end='\n***********\n')
#print('Mean = ',tf.math.reduce_mean(x))
#print('Max Location = ',tf.argmax(x))
#x_squeezed = tf.squeeze(x)
#print('squeezed shape ',tf.squeeze(x_squeezed ).shape)
#print('Max value = ',tf.argmax(x))
#print('add_n = ', tf.math.add_n(x))
#print('add random number = ', tf.math.add(x,tf.cast(tf.random.uniform(shape=[52,7],minval=5,maxval=200),tf.int16)))
print('numpy = ', x.numpy)

numpy =  <bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(52, 7), dtype=int16, numpy=
array([[134,  90,  73,  95,  11, 138, 149],
       [175,  49,  48,  65, 145,  30, 111],
       [117, 180,   6, 106, 128,  43, 147],
       [111,  25, 136, 133,  70, 122,  46],
       [171,  90, 189,  51, 163, 107, 101],
       [ 47, 169, 175,  65, 138,  51, 157],
       [193,  18, 160, 133, 119,  37, 148],
       [ 67, 123,  95, 195, 145,  68, 166],
       [102,  42, 152,  70,  59,  66, 123],
       [151, 102,  40,  30, 131, 191, 135],
       [ 64,  76,  92,  40, 108, 142, 180],
       [ 66, 126, 193,  26,  62, 187,  31],
       [ 67,  56,  11, 180, 129, 118,  45],
       [144,  75,  14,  34, 169, 187,  23],
       [ 21, 126,  77, 105, 126, 161,  37],
       [ 48, 126,  22, 184, 187, 122,  98],
       [ 33,  68, 185, 156, 129, 127,  74],
       [ 85,  26,  32,  41, 139, 145,  53],
       [120, 102, 180,  28,  31,  54, 102],
       [145, 105, 114, 119,  51, 182, 174],
       [149, 107,  49,  

In [ ]:
list=[0,1,2,3,4,5]
tf.one_hot(list,depth=6)

<tf.Tensor: shape=(6, 6), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]], dtype=float32)>

In [ ]:
tf.config.list_physical_devices()
!cat /etc/os-release



PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
